services:
  postgres:
    image: postgres:16-alpine
    container_name: b_auto_ops_pg
    environment:
      POSTGRES_USER: ops
      POSTGRES_PASSWORD: ops
      POSTGRES_DB: ops
    ports:
      - "5432:5432"
    volumes:
      - b_auto_ops_pg:/var/lib/postgresql/data

volumes:
  b_auto_ops_pg:
